module.exports = [ { type: 'tag',
    name: 'a',
    attribs: { href: '/en', id: 'logo' },
    children: [ [Object], [Object], [Object] ],
    next:
     { data: '\n  \n      ',
       type: 'text',
       next: [Object],
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n  \n      ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'div',
       attribs: [Object],
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: '/en/' },
    children: [ [Object] ],
    next:
     { data: '\n          ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n            ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: [Object],
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: '/en/about/' },
    children: [ [Object] ],
    next:
     { data: '\n            ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n              ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: '/en/download/' },
    children: [ [Object] ],
    next:
     { data: '\n            ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n              ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: '/en/docs/' },
    children: [ [Object] ],
    next:
     { data: '\n            ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n              ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: '/en/foundation/' },
    children: [ [Object] ],
    next:
     { data: '\n            ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n              ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: '/en/get-involved/' },
    children: [ [Object] ],
    next:
     { data: '\n            ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n              ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: '/en/security/' },
    children: [ [Object] ],
    next:
     { data: '\n            ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n              ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: '/en/blog/' },
    children: [ [Object] ],
    next:
     { data: '\n            ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n              ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://developers.google.com/v8/' },
    children: [ [Object] ],
    next:
     { data: '.\nNode.js uses an event-driven, non-blocking I/O model that makes it\nlightweight and efficient. Node.js\' package ecosystem, ',
       type: 'text',
       next: [Object],
       prev: [],
       parent: [Object] },
    prev:
     { data: 'Node.js® is a JavaScript runtime built on ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'p',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://www.npmjs.com/' },
    children: [ [Object] ],
    next:
     { data: ', is the largest ecosystem of open\nsource libraries in the world.',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '.\nNode.js uses an event-driven, non-blocking I/O model that makes it\nlightweight and efficient. Node.js\' package ecosystem, ',
       type: 'text',
       next: [],
       prev: [Object],
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'p',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs:
     { href: 'https://nodejs.org/dist/v6.10.0/',
       class: 'home-downloadbutton',
       title: 'Download v6.10.0 LTS',
       'data-version': 'v6.10.0' },
    children: [ [Object], [Object], [Object] ],
    next:
     { data: '\n\n          ',
       type: 'text',
       next: [Object],
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n\n          ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'div',
       attribs: [Object],
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://nodejs.org/en/download/' },
    children: [ [Object] ],
    next:
     { data: '\n            ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n              ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.10.0' },
    children: [ [Object] ],
    next:
     { data: '\n            ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n              ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://nodejs.org/dist/latest-v6.x/docs/api/' },
    children: [ [Object] ],
    next:
     { data: '\n            ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n              ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs:
     { href: 'https://nodejs.org/dist/v7.7.2/',
       class: 'home-downloadbutton',
       title: 'Download v7.7.2 Current',
       'data-version': 'v7.7.2' },
    children: [ [Object], [Object], [Object] ],
    next:
     { data: '\n\n            ',
       type: 'text',
       next: [Object],
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n\n            ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'div',
       attribs: [Object],
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://nodejs.org/en/download/current/' },
    children: [ [Object] ],
    next:
     { data: '\n              ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n                ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#7.7.2' },
    children: [ [Object] ],
    next:
     { data: '\n              ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n                ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://nodejs.org/dist/latest-v7.x/docs/api/' },
    children: [ [Object] ],
    next:
     { data: '\n              ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n                ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://github.com/nodejs/LTS#lts-schedule' },
    children: [ [Object] ],
    next:
     { data: '\n        ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n          Or have a look at the ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'p',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: '#', id: 'scroll-to-top' },
    children: [ [Object], [Object] ],
    next:
     { data: '\n  \n  ',
       type: 'text',
       next: [Object],
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n\n  ',
       type: 'text',
       next: [],
       prev: [Object],
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'body',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs:
     { class: 'linuxfoundation-logo',
       href: 'http://collabprojects.linuxfoundation.org' },
    children: [ [Object], [Object], [Object] ],
    next:
     { data: '\n          ',
       type: 'text',
       next: [Object],
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n          ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'div',
       attribs: [Object],
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://github.com/nodejs/node/issues' },
    children: [ [Object] ],
    next: null,
    prev: null,
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://github.com/nodejs/nodejs.org/issues' },
    children: [ [Object] ],
    next: null,
    prev: null,
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://github.com/nodejs/help/issues' },
    children: [ [Object] ],
    next: null,
    prev: null,
    parent:
     { type: 'tag',
       name: 'li',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: '/static/documents/trademark-policy.pdf' },
    children: [ [Object] ],
    next:
     { data: '.',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: 'Node.js is a trademark of Joyent, Inc. and is used with its permission. Please review the ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'p',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs:
     { href: 'http://www.linuxfoundation.org/programs/legal/trademark',
       title: 'Linux Mark Institute' },
    children: [ [Object] ],
    next:
     { data: ' of Linus Torvalds.',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: 'Linux is a registered ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'p',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } },
  { type: 'tag',
    name: 'a',
    attribs: { href: 'https://raw.githubusercontent.com/nodejs/node/master/LICENSE' },
    children: [ [Object] ],
    next:
     { data: '.\n        ',
       type: 'text',
       next: null,
       prev: [],
       parent: [Object] },
    prev:
     { data: '\n          ',
       type: 'text',
       next: [],
       prev: null,
       parent: [Object] },
    parent:
     { type: 'tag',
       name: 'p',
       attribs: {},
       children: [Object],
       next: [Object],
       prev: [Object],
       parent: [Object] } } ];
